
export const coursesData = [
  { title: 'Artificial Intelligence', details: 'A Course on Artificial Intelligence by XXX', key: '1' },
  { title: 'Machine Learning', details: 'A Course on Machine Learning by XXX', key: '2' },
  { title: 'OOP', details: 'A Course on OOP by XXX', key: '3' },
  { title: 'Web Development', details: 'A Course on Web Development by XXX', key: '4' },
  { title: 'Mobile Development', details: 'A Course on Mobile Development by XXX', key: '5' },
]

const randText = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam amet autem necessitatibus. Dicta beatae veniam aliquam sit fuga ea voluptates corporis necessitatibus labore, laborum odio deleniti perferendis rem incidunt velit?'
export const articleData = [
  { title: 'Artificial Intelligence breackthrough!!', 
    details: randText, 
    image: require('../assets/data/Resources.png'),
    userID: 'Susu',
    userPic: require('../assets/data/profilepic.png'),
    likes: '21',
    date: '21 May 2020',
    key: '21' },
  { title: 'What is Computer Science?', 
    details: randText, 
    image: require('../assets/data/Challenges.png'),
    userID: 'Susu',
    userPic: require('../assets/data/profilepic.png'),
    likes: '21',
    date: '21 May 2020',
    key: '22' },
  { title: 'How to start my programming journey', 
    details: randText, 
    image: require('../assets/data/Resources.png'),
    userID: 'Susu',
    userPic: require('../assets/data/profilepic.png'),
    likes: '121',
    date: '21 May 2020',
    key: '23' },
  { title: 'Tips and Tricks to Debug', 
    details: randText, 
    image: require('../assets/data/Challenges.png'),
    userID: 'Susu',
    userPic: require('../assets/data/profilepic.png'),
    likes: '213',
    date: '23 May 2020',
    key: '24' },
  { title: 'Advice for beginners', 
    details: randText, 
    image: require('../assets/data/Resources.png'),
    userID: 'Susu',
    userPic: require('../assets/data/profilepic.png'),
    likes: '21',
    date: '21 May 2020',
    key: '25' },
]